import { resolve } from "node:path";
import { existsSync, readFileSync, readdirSync, mkdirSync, writeFileSync } from "node:fs";
import pc from "picocolors";
import { loadConfig } from "../utils/config.js";
import { type RunState, allCriteriaPassed } from "@goalrun/core";

export async function auditCommand(
  runId: string,
  opts: { json?: boolean; output?: string },
): Promise<void> {
  const repoRoot = process.cwd();
  const config = loadConfig(repoRoot);
  const runDir = resolve(repoRoot, config.runs_dir, runId);
  const statusPath = resolve(runDir, "status.json");

  if (!existsSync(statusPath)) {
    console.error(pc.red(`Run "${runId}" not found.`));
    process.exit(1);
  }

  let state: RunState;
  try {
    state = JSON.parse(readFileSync(statusPath, "utf-8")) as RunState;
  } catch {
    console.error(pc.red(`Failed to parse status.json for "${runId}"`));
    process.exit(1);
  }

  const criteriaPassed = allCriteriaPassed(state);
  const verdict = criteriaPassed ? "PASSED" : "FAILED";

  const lines = [
    `# GoalRun Audit Report`,
    ``,
    `## Summary`,
    `- **Run ID**: ${state.run_id}`,
    `- **Goal**: ${state.goal_id}`,
    `- **Status**: ${state.status}`,
    `- **Iterations**: ${state.iteration}/${state.max_iterations}`,
    `- **Checkpoints**: ${state.checkpoints.length}`,
    `- **Verdict**: ${verdict}`,
    ``,
    `## Criteria`,
  ];

  for (const c of state.criteria) {
    const icon = c.status === "pass" ? "✅" : c.status === "fail" ? "❌" : "⏳";
    lines.push(`- ${icon} ${c.text}`);
  }

  lines.push(
    ``,
    `## Policy Gates`,
  );
  for (const g of state.policy_gates) {
    lines.push(`- ⚑ ${g}`);
  }

  lines.push(
    ``,
    `## Checkpoints`,
  );
  for (const cp of state.checkpoints) {
    lines.push(`- **${cp.id}** → ${cp.status}${cp.summary ? ` — ${cp.summary}` : ""}`);
  }

  lines.push(
    ``,
    `## Evidence`,
  );
  const evidenceDir = resolve(runDir, "verification");
  if (existsSync(evidenceDir)) {
    const files = readdirSync(evidenceDir);
    if (files.length > 0) {
      for (const f of files) lines.push(`- 📄 ${f}`);
    } else {
      lines.push(`⚠️ No evidence files found. Verification claims are unverified.`);
    }
  } else {
    lines.push(`⚠️ No verification/ directory. All claims are marked as unverified.`);
  }

  lines.push(
    ``,
    `---`,
    `Generated by GoalRun — ${new Date().toISOString()}`,
  );

  const report = lines.join("\n");

  if (opts.output) {
    const outPath = resolve(repoRoot, opts.output);
    mkdirSync(resolve(outPath, ".."), { recursive: true });
    writeFileSync(outPath, report, "utf-8");
    console.log(pc.green(`Audit report written to: ${outPath}`));
  }

  if (opts.json) {
    console.log(JSON.stringify({
      run_id: state.run_id,
      goal_id: state.goal_id,
      verdict,
      criteria: state.criteria,
      checkpoints: state.checkpoints.length,
      status: state.status,
    }, null, 2));
  } else {
    console.log(report);
  }
}
