import { resolve } from 'node:path';
import { writeFileSync, mkdirSync } from 'node:fs';
import pc from 'picocolors';
import { detectEcosystem, generateBootstrapPlan } from 'goalrun-core';

export async function ecosystemCommand(
  subcommand: string,
  opts: { json?: boolean; force?: boolean },
): Promise<void> {
  const repoRoot = process.cwd();

  switch (subcommand) {
    case 'detect':
      await detectSubcommand(repoRoot, opts);
      break;
    case 'bootstrap':
      await bootstrapSubcommand(repoRoot, opts);
      break;
    case 'status':
      await statusSubcommand(repoRoot, opts);
      break;
    default:
      console.error(pc.red(`Unknown subcommand: ${subcommand}`));
      console.log(pc.dim('Available subcommands: detect, bootstrap, status'));
      process.exit(1);
  }
}

async function detectSubcommand(repoRoot: string, opts: { json?: boolean }): Promise<void> {
  const detection = detectEcosystem(repoRoot);

  if (opts.json) {
    console.log(JSON.stringify(detection, null, 2));
    return;
  }

  console.log(pc.bold('Ecosystem Detection:'));
  console.log('');

  const components = [
    {
      name: 'Superpowers',
      installed: detection.superpowers,
      desc: 'TDD, verification, code-review skills',
    },
    {
      name: 'OMC (Oh-My-ClaudeCode)',
      installed: detection.omc,
      desc: 'ralph, ultrawork, team execution modes',
    },
    { name: 'OpenSpec', installed: detection.openspec, desc: 'Change lifecycle tracking' },
    {
      name: 'gstack',
      installed: detection.gstack,
      desc: 'Role-based review (/ship, /review, /qa, /cso)',
    },
    { name: 'ECC', installed: detection.ecc, desc: 'Language-specific rules, hooks, and agents' },
  ];

  for (const comp of components) {
    const icon = comp.installed ? pc.green('✓') : pc.yellow('○');
    const status = comp.installed ? pc.green('installed') : pc.yellow('missing');
    console.log(`  ${icon} ${comp.name} — ${status}`);
    if (!comp.installed) {
      console.log(pc.dim(`    ${comp.desc}`));
    }
  }

  const installed = components.filter((c) => c.installed).length;
  console.log('');
  console.log(`${installed}/${components.length} components installed`);

  if (installed < components.length) {
    console.log('');
    console.log(pc.dim('Run `goalrun ecosystem bootstrap` to auto-install missing components.'));
  }
}

async function bootstrapSubcommand(
  repoRoot: string,
  opts: { json?: boolean; force?: boolean },
): Promise<void> {
  const detection = detectEcosystem(repoRoot);
  const plan = generateBootstrapPlan(detection);

  if (plan.missing.length === 0) {
    console.log(pc.green('All ecosystem components are already installed!'));
    if (opts.json) {
      console.log(JSON.stringify({ status: 'complete', missing: [] }, null, 2));
    }
    return;
  }

  if (opts.json) {
    console.log(JSON.stringify(plan, null, 2));
    return;
  }

  console.log(pc.bold('Bootstrap Plan:'));
  console.log(`${plan.missing.length} component(s) to install:`);
  console.log('');

  for (const action of plan.actions) {
    const priority =
      action.priority === 'required'
        ? pc.red('[required]')
        : action.priority === 'recommended'
          ? pc.yellow('[recommended]')
          : pc.dim('[optional]');
    console.log(`  ${priority} ${action.component}`);
    console.log(`    ${action.description}`);
    console.log(pc.dim(`    ${action.command}`));
    console.log('');
  }

  // Generate bootstrap instructions file
  const bootstrapPath = resolve(repoRoot, '.goalrun', 'ecosystem-bootstrap.md');
  mkdirSync(resolve(bootstrapPath, '..'), { recursive: true });

  const content = [
    '# Ecosystem Bootstrap Instructions',
    '',
    '> Generated by `goalrun ecosystem bootstrap`',
    '',
    '## Missing Components',
    '',
    ...plan.actions.map(
      (a) =>
        `### ${a.component} (${a.priority})\n\n${a.description}\n\n\`\`\`\n${a.command}\n\`\`\``,
    ),
    '',
    '## Quick Start (Claude Code)',
    '',
    'Run these commands in order:',
    '',
    ...plan.actions.map((a, i) => `${i + 1}. \`${a.command}\``),
    '',
    '## What Each Component Does',
    '',
    '| Component | Purpose |',
    '|-----------|---------|',
    '| Superpowers | TDD, verification, code-review, brainstorming, worktree skills |',
    '| OMC | ralph (TDD loop), ultrawork (parallel), team (multi-agent review) |',
    '| OpenSpec | Change lifecycle: explore → propose → apply → archive |',
    '| gstack | Role-based review: /ship, /review, /qa, /cso |',
    '| ECC | Language-specific rules, hooks, and agent orchestration |',
    '',
  ].join('\n');

  writeFileSync(bootstrapPath, content, 'utf-8');

  console.log(pc.green(`Bootstrap instructions written to: ${bootstrapPath}`));
  console.log('');
  console.log(pc.dim('Follow the instructions to install missing components.'));
  console.log(pc.dim('After installation, run `goalrun ecosystem detect` to verify.'));
}

async function statusSubcommand(repoRoot: string, opts: { json?: boolean }): Promise<void> {
  const detection = detectEcosystem(repoRoot);
  const plan = generateBootstrapPlan(detection);

  const components = [
    {
      name: 'Superpowers',
      key: 'superpowers' as const,
      installed: detection.superpowers,
      desc: 'TDD, verification, code-review, brainstorming skills',
      healthCheck: () => detection.superpowers,
    },
    {
      name: 'OMC (Oh-My-ClaudeCode)',
      key: 'omc' as const,
      installed: detection.omc,
      desc: 'ralph, ultrawork, team execution modes',
      healthCheck: () => detection.omc,
    },
    {
      name: 'OpenSpec',
      key: 'openspec' as const,
      installed: detection.openspec,
      desc: 'Change lifecycle: explore → propose → apply → archive',
      healthCheck: () => detection.openspec,
    },
    {
      name: 'gstack',
      key: 'gstack' as const,
      installed: detection.gstack,
      desc: 'Role-based review: /ship, /review, /qa, /cso',
      healthCheck: () => detection.gstack,
    },
    {
      name: 'ECC',
      key: 'ecc' as const,
      installed: detection.ecc,
      desc: 'Language-specific rules, hooks, and agent orchestration',
      healthCheck: () => detection.ecc,
    },
  ];

  if (opts.json) {
    const status = {
      components: components.map((c) => ({
        name: c.name,
        installed: c.installed,
        healthy: c.healthCheck(),
        description: c.desc,
      })),
      missing: plan.missing,
      allInstalled: plan.missing.length === 0,
    };
    console.log(JSON.stringify(status, null, 2));
    return;
  }

  console.log(pc.bold('Ecosystem Status'));
  console.log('');

  const installedCount = components.filter((c) => c.installed).length;
  const totalCount = components.length;

  for (const comp of components) {
    const icon = comp.installed ? pc.green('✓') : pc.red('✗');
    const statusText = comp.installed ? pc.green('installed') : pc.red('missing');
    console.log(`  ${icon} ${comp.name} — ${statusText}`);
    console.log(pc.dim(`    ${comp.desc}`));
  }

  console.log('');
  console.log(`${installedCount}/${totalCount} components installed`);

  if (plan.missing.length > 0) {
    console.log('');
    console.log(pc.yellow('Missing components:'));
    for (const action of plan.actions) {
      const priority =
        action.priority === 'required'
          ? pc.red('[required]')
          : action.priority === 'recommended'
            ? pc.yellow('[recommended]')
            : pc.dim('[optional]');
      console.log(`  ${priority} ${action.component}: ${action.description}`);
      console.log(pc.dim(`    Install: ${action.command}`));
    }

    console.log('');
    console.log(
      pc.dim('Run `goalrun ecosystem bootstrap` for detailed installation instructions.'),
    );
  } else {
    console.log('');
    console.log(pc.green('All ecosystem components are installed and healthy!'));
  }

  // Show diagnostics
  if (detection.diagnostics.length > 0) {
    console.log('');
    console.log(pc.bold('Diagnostics:'));
    for (const d of detection.diagnostics) {
      const icon =
        d.severity === 'error'
          ? pc.red('✗')
          : d.severity === 'warning'
            ? pc.yellow('!')
            : pc.blue('i');
      console.log(`  ${icon} ${d.message}`);
      if (d.hint) console.log(pc.dim(`    ${d.hint}`));
    }
  }
}
