export const TARGETS = ['claude', 'codex', 'cursor', 'opencode'] as const;
export type HandoffTarget = (typeof TARGETS)[number];

export interface HandoffPlan {
  goalId: string;
  goalTitle: string;
  selectedSkills: string[];
  policyGates: string[];
  verificationChecklist: string[];
  riskSummary: string[];
  diagnostics: { code: string; severity: string; message: string; hint?: string }[];
  agentPrompt: string;
}

const TARGET_CONFIGS: Record<
  HandoffTarget,
  { name: string; configFile: string; skillPath: string }
> = {
  claude: { name: 'Claude Code', configFile: 'CLAUDE.md', skillPath: '.claude/skills/' },
  codex: { name: 'Codex CLI', configFile: '.codex/config.yaml', skillPath: '.codex/skills/' },
  cursor: { name: 'Cursor', configFile: '.cursorrules', skillPath: '.cursor/skills/' },
  opencode: {
    name: 'OpenCode',
    configFile: '.opencode/config.yaml',
    skillPath: '.opencode/skills/',
  },
};

export function generateHandoff(plan: HandoffPlan, target: HandoffTarget): string {
  const cfg = TARGET_CONFIGS[target];
  if (!cfg) {
    throw new Error(`Unsupported target: "${target}". Supported: ${TARGETS.join(', ')}`);
  }

  const lines = [
    `# Engineering Task: ${plan.goalTitle}`,
    `# Target: ${cfg.name}`,
    `# Goal ID: ${plan.goalId}`,
    ``,
    `## Context`,
    `This plan was generated by GoalRun for execution with ${cfg.name}.`,
    `Skill files are located in .agent/skills/<name>/SKILL.md.`,
    `Refer to ${cfg.configFile} for project-level agent configuration.`,
    ``,
    `## Skills (in order)`,
    ...plan.selectedSkills.map((s, i) => `${i + 1}. ${s} — read .agent/skills/${s}/SKILL.md`),
    ``,
    `## Policy Gates (STOP and request approval at each)`,
    ...plan.policyGates.map((g) => `- [ ] ${g}`),
    ``,
    `## Verification Checklist (run after each change)`,
    ...plan.verificationChecklist.map((c) => `- [ ] ${c}`),
    ``,
    `## Risk Summary`,
    ...plan.riskSummary.map((r) => `- ${r}`),
    ``,
    `## Instructions for ${cfg.name}`,
  ];

  // Target-specific instructions
  switch (target) {
    case 'claude':
      lines.push(
        `1. Read each skill's SKILL.md from .agent/skills/<name>/SKILL.md`,
        `2. Follow the skill workflows in the specified order`,
        `3. Honor the policy gates — stop and ask for approval before proceeding`,
        `4. After each change, run the verification checklist commands`,
        `5. Use ${cfg.configFile} for project-level context`,
        `6. Report results against each criterion in the goal spec`,
      );
      break;
    case 'codex':
      lines.push(
        `1. Load each skill from .codex/skills/<name>/SKILL.md`,
        `2. Execute skill workflows sequentially`,
        `3. Pause at policy gates for human approval`,
        `4. Run verification commands after each iteration`,
        `5. Reference ${cfg.configFile} for Codex configuration`,
      );
      break;
    case 'cursor':
      lines.push(
        `1. Open each SKILL.md from .agent/skills/<name>/SKILL.md`,
        `2. Apply skills in the listed order`,
        `3. Respect policy gates — request approval before high-risk changes`,
        `4. Use ${cfg.configFile} for Cursor rules reference`,
        `5. Verify with the checklist commands after each change`,
      );
      break;
    case 'opencode':
      lines.push(
        `1. Load skill definitions from .opencode/skills/<name>/SKILL.md`,
        `2. Follow the workflow for each skill in sequence`,
        `3. Stop at each policy gate and wait for confirmation`,
        `4. Execute verification commands and capture output`,
        `5. Reference ${cfg.configFile} for OpenCode settings`,
      );
      break;
  }

  lines.push(``, `## Validation Diagnostics (from GoalRun harnesses)`);

  if (plan.diagnostics.length === 0) {
    lines.push(`All harness checks passed. No issues found.`);
  } else {
    for (const d of plan.diagnostics) {
      lines.push(
        `- [${d.severity.toUpperCase()}] ${d.code}: ${d.message}${d.hint ? ` (Hint: ${d.hint})` : ''}`,
      );
    }
  }

  lines.push(
    ``,
    `---`,
    `Generated by GoalRun — goal-driven agent skills for software engineering`,
    `https://github.com/strings77wzq/goal-run`,
  );

  return lines.join('\n');
}
