export const TARGETS = ['claude', 'codex', 'cursor', 'opencode'] as const;
export type HandoffTarget = (typeof TARGETS)[number];

export interface HandoffPlan {
  goalId: string;
  goalTitle: string;
  selectedSkills: string[];
  policyGates: string[];
  verificationChecklist: string[];
  riskSummary: string[];
  diagnostics: { code: string; severity: string; message: string; hint?: string }[];
  ecosystem?: {
    superpowers: boolean;
    omc: boolean;
    openspec: boolean;
    gstack: boolean;
    ecc: boolean;
  };
  contextMd?: string;
  architectureMd?: string;
  lessons?: { pattern: string; lesson: string; severity: string }[];
}

const TARGET_CONFIGS: Record<
  HandoffTarget,
  { name: string; configFile: string; skillPath: string }
> = {
  claude: { name: 'Claude Code', configFile: 'CLAUDE.md', skillPath: '.claude/skills/' },
  codex: { name: 'Codex CLI', configFile: '.codex/config.yaml', skillPath: '.codex/skills/' },
  cursor: { name: 'Cursor', configFile: '.cursorrules', skillPath: '.cursor/skills/' },
  opencode: {
    name: 'OpenCode',
    configFile: '.opencode/config.yaml',
    skillPath: '.opencode/skills/',
  },
};

export function generateHandoff(plan: HandoffPlan, target: HandoffTarget): string {
  const cfg = TARGET_CONFIGS[target];
  if (!cfg) {
    throw new Error(`Unsupported target: "${target}". Supported: ${TARGETS.join(', ')}`);
  }

  const lines = [
    `# Engineering Task: ${plan.goalTitle}`,
    `# Target: ${cfg.name}`,
    `# Goal ID: ${plan.goalId}`,
    ``,
    `## Context`,
    `This plan was generated by GoalRun for execution with ${cfg.name}.`,
    `Skill files are located in ${cfg.skillPath}<name>/SKILL.md.`,
    `Refer to ${cfg.configFile} for project-level agent configuration.`,
    ``,
    `## Skills (in order)`,
    ...plan.selectedSkills.map((s, i) => `${i + 1}. ${s} — read ${cfg.skillPath}${s}/SKILL.md`),
    ``,
    `## Policy Gates (STOP and request approval at each)`,
    ...plan.policyGates.map((g) => `- [ ] ${g}`),
    ``,
    `## Verification Checklist (run after each change)`,
    ...plan.verificationChecklist.map((c) => `- [ ] ${c}`),
    ``,
    `## Risk Summary`,
    ...plan.riskSummary.map((r) => `- ${r}`),
    ``,
    `## Instructions for ${cfg.name}`,
  ];

  // Target-specific instructions
  switch (target) {
    case 'claude':
      lines.push(
        `1. Read each skill's SKILL.md from ${cfg.skillPath}<name>/SKILL.md`,
        `2. Follow the skill workflows in the specified order`,
        `3. Honor the policy gates — stop and ask for approval before proceeding`,
        `4. After each change, run the verification checklist commands`,
        `5. Use ${cfg.configFile} for project-level context`,
        `6. Report results against each criterion in the goal spec`,
      );
      break;
    case 'codex':
      lines.push(
        `1. Load each skill from ${cfg.skillPath}<name>/SKILL.md`,
        `2. Execute skill workflows sequentially`,
        `3. Pause at policy gates for human approval`,
        `4. Run verification commands after each iteration`,
        `5. Reference ${cfg.configFile} for Codex configuration`,
      );
      break;
    case 'cursor':
      lines.push(
        `1. Open each SKILL.md from ${cfg.skillPath}<name>/SKILL.md`,
        `2. Apply skills in the listed order`,
        `3. Respect policy gates — request approval before high-risk changes`,
        `4. Use ${cfg.configFile} for Cursor rules reference`,
        `5. Verify with the checklist commands after each change`,
      );
      break;
    case 'opencode':
      lines.push(
        `1. Load skill definitions from ${cfg.skillPath}<name>/SKILL.md`,
        `2. Follow the workflow for each skill in sequence`,
        `3. Stop at each policy gate and wait for confirmation`,
        `4. Execute verification commands and capture output`,
        `5. Reference ${cfg.configFile} for OpenCode settings`,
      );
      break;
  }

  // Ecosystem integration section
  if (plan.ecosystem) {
    lines.push(``, `## Ecosystem Components`);
    const components = [
      { key: 'superpowers' as const, name: 'Superpowers', usage: 'TDD, verification-before-completion, requesting-code-review, brainstorming' },
      { key: 'omc' as const, name: 'Oh-My-ClaudeCode (OMC)', usage: 'ralph (TDD loop), ultrawork (parallel), team (multi-agent review)' },
      { key: 'openspec' as const, name: 'OpenSpec', usage: 'Change lifecycle: explore → propose → apply → archive' },
      { key: 'gstack' as const, name: 'gstack', usage: 'Role-based review: /ship, /review, /qa, /cso' },
      { key: 'ecc' as const, name: 'ECC', usage: 'Language-specific rules, hooks, and agent orchestration' },
    ];
    for (const comp of components) {
      const status = plan.ecosystem[comp.key] ? '✅ Installed' : '❌ Not installed';
      lines.push(`- **${comp.name}**: ${status}`);
      if (plan.ecosystem[comp.key]) {
        lines.push(`  - Use: ${comp.usage}`);
      }
    }
  }

  // Project context section
  if (plan.contextMd) {
    lines.push(``, `## Project Context (from .goalrun/CONTEXT.md)`, ``);
    // Truncate if very long
    const contextLines = plan.contextMd.split('\n');
    if (contextLines.length > 100) {
      lines.push(...contextLines.slice(0, 100), '', `> ... (${contextLines.length - 100} more lines. Read .goalrun/CONTEXT.md for full context.)`);
    } else {
      lines.push(plan.contextMd);
    }
  }

  // Architecture constraints section
  if (plan.architectureMd) {
    lines.push(``, `## Architecture Constraints (from .goalrun/ARCHITECTURE.md)`, ``);
    const archLines = plan.architectureMd.split('\n');
    if (archLines.length > 80) {
      lines.push(...archLines.slice(0, 80), '', `> ... (${archLines.length - 80} more lines. Read .goalrun/ARCHITECTURE.md for full architecture.)`);
    } else {
      lines.push(plan.architectureMd);
    }
  }

  // Lessons section
  if (plan.lessons && plan.lessons.length > 0) {
    lines.push(``, `## Lessons Learned (from .goalrun/lessons.json)`, ``);
    lines.push('> **Check these BEFORE writing code.** These are failure patterns from previous runs.', '');
    for (const lesson of plan.lessons.slice(0, 10)) {
      lines.push(`- [${lesson.severity.toUpperCase()}] **${lesson.pattern}**: ${lesson.lesson}`);
    }
    if (plan.lessons.length > 10) {
      lines.push(`- ... and ${plan.lessons.length - 10} more. Search with: goalrun lessons search <keyword>`);
    }
  }

  lines.push(``, `## Validation Diagnostics (from GoalRun harnesses)`);

  if (plan.diagnostics.length === 0) {
    lines.push(`All harness checks passed. No issues found.`);
  } else {
    for (const d of plan.diagnostics) {
      lines.push(
        `- [${d.severity.toUpperCase()}] ${d.code}: ${d.message}${d.hint ? ` (Hint: ${d.hint})` : ''}`,
      );
    }
  }

  // Context window reset protocol
  lines.push(
    ``,
    `## Context Window Reset Protocol`,
    '',
    'If your context window fills up or you detect looping:',
    '1. **Before clearing**: PROGRESS.md has been auto-generated with current state.',
    '2. **After clearing**: Reload in order: CONTEXT.md → ARCHITECTURE.md → lessons.json → PROGRESS.md → SKILL.md',
    '3. **Before retrying**: Check "Excluded Approaches" in PROGRESS.md.',
    '4. **Do not blind-retry**: Same error 3 times = stop and escalate.',
  );

  lines.push(
    ``,
    `---`,
    `Generated by GoalRun — goal-driven agent skills for software engineering`,
    `https://github.com/strings77wzq/goal-run`,
  );

  return lines.join('\n');
}
